# Dockerfile.mysql
FROM mysql:8.0

# Make the "en_US.UTF-8" locale to let mysql to enable utf-8 by default
RUN apt-get update && \
    apt-get install -y locales && \
    rm -rf /var/lib/apt/lists/* $ && \
    localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG=C.UTF-8

