version: '3'
services:
  ocr-tesseract:
    build: ocr-tesseract
    container_name: ocr-tesseract-daemon
    volumes:
      - /ocr/tess-ta/tessdata:/ocr/tess-ta/tessdata
      - /ocr/tess-ta/storage:/ocr/tess-ta/storage
  ocr-mysql:
    image: mysql:8.0.16
    container_name: ocr-mysql-daemon
    hostname: ocr-mysql-daemon
    command: mysqld --user=root --verbose
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "tesseract_ta"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    expose:
      - "3306"
  ocr-tessta:
    build: .
    container_name: ocr-tessta-daemon
    hostname: ocr-tessta-daemon
    ports:
      - "80:4000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - /ocr/tess-ta/tessdata:/ocr/tess-ta/tessdata
      - /ocr/tess-ta/storage:/ocr/tess-ta/storage
    depends_on:
      - ocr-tesseract
      - ocr-mysql