version: '3'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql-daemon
    hostname: mysql-daemon
    # command: mysqld --user=root --verbose
    command: [
      'mysqld', '--character-set-server=utf8',
      '--default-authentication-plugin=mysql_native_password'
    ]
    volumes:
      - "./database:/docker-entrypoint-initdb.d"
      - "~/ocr/mysql:/var/lib/mysql"
    ports:
      - "3306"
    environment:
      MYSQL_DATABASE: "tesseract_ta"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "tessuser"
      MYSQL_PASSWORD: "leonie-mysql@ocr"
    expose:
      - "3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    container_name: phpmyadmin-daemon
    hostname: phpmyadmin-daemon
    environment:
      MYSQL_USER: "tessuser"
      MYSQL_PASSWORD: "leonie-mysql@ocr"
      PMA_HOST: "mysql"
    ports:
      - "4001:80"
    depends_on:
      - mysql
  tessta:
    build: .
    container_name: tessta-daemon
    hostname: tessta-daemon
    ports:
      - "4000"
      - "80:4000"
    volumes:
      - "~/ocr/tessdata:/ocr/tessdata"
      - "~/ocr/storage:/ocr/storage"
    depends_on:
      - mysql