# Server
server:
    port: 4000

# Spring
spring:
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    security:
        oauth2:
            client:
                registration:
                    google:
                        clientId: 649193414368-9g4ksk2r1fi9goqto8k41k4loj594s39.apps.googleusercontent.com
                        clientSecret: 6BNqVbWWwze-YE_S98Zc1-a6
                        scope:
                            - email
                            - profile

app:
    # Store
    tessdata: ~/ocr/tessdata
    tempstore: ~/ocr/storage

    # MySQL
    mysql-uri: jdbc:mysql://localhost:3306/tesseract_ta?allowPublicKeyRetrieval=true&useSSL=false
    mysql-user: root
    mysql-password:

---
spring:
    profiles: release

app:
    # MySQL
    mysql-uri: jdbc:mysql://mysql-daemon:3306/tesseract_ta?allowPublicKeyRetrieval=true&useSSL=false
    mysql-user: tessuser
    mysql-password: leonie-mysql@ocr