server:
    port: 4000
spring:
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    security:
        oauth2:
            client:
                registration:
                    google:
                        clientId: 649193414368-9g4ksk2r1fi9goqto8k41k4loj594s39.apps.googleusercontent.com
                        clientSecret: 6BNqVbWWwze-YE_S98Zc1-a6
                        scope:
                            - email
                            - profile
app:
    auth:
        tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
        tokenExpirationMsec: 864000000
    oauth2:
        authorizedRedirectUris:
            - http://localhost:4000/oauth2/redirect
            - ocrsrilanka://oauth2/redirect
    store:
        tessdata: ~/ocr/tessdata
        tempstore: ~/ocr/storage
    mysql:
        uri: jdbc:mysql://localhost:3306/tesseract_ta?allowPublicKeyRetrieval=true&useSSL=false
        user: root
        password:

---
spring:
    profiles: release

app:
    mysql:
        uri: jdbc:mysql://mysql-daemon:3306/tesseract_ta?allowPublicKeyRetrieval=true&useSSL=false
        user: tessuser
        password: leonie-mysql@ocr